# Generated by Django 5.0.3 on 2024-04-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="userprofiles/default.jpg",
                null=True,
                upload_to="static/images/userprofiles",
            ),
        ),
    ]
