# Generated by Django 5.0.3 on 2024-04-29 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0003_post_heaader_image_alter_post_title_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="heaader_image",
            new_name="header_image",
        ),
    ]
