# Generated by Django 5.0.3 on 2024-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0006_profile_profile_pic_profile_venmo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pinterest_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
