# Generated by Django 5.0.3 on 2024-05-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0007_profile_pinterest_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
